// Generated by CoffeeScript 1.9.2
var isCompatible;

isCompatible = require('./core');

module.exports = function(chai, utils) {
  return chai.Assertion.addMethod('compatible', function(expects) {
    var msg, path, ref;
    ref = isCompatible(this._obj, expects), isCompatible = ref.isCompatible, path = ref.path;
    msg = "expect " + (JSON.stringify(this._obj)) + " to be type compatible with: " + (JSON.stringify(expects));
    if (path) {
      msg += "\n\tbut fail at the key: " + path;
    }
    return chai.assert(isCompatible === true, msg);
  });
};
