// Generated by CoffeeScript 1.9.2
var orderKey;

orderKey = function(obj, orders) {
  var i, key, len, value;
  for (i = 0, len = orders.length; i < len; i++) {
    key = orders[i];
    if (key in obj) {
      value = obj[key];
      delete obj[key];
      obj[key] = value;
    }
  }
};

module.exports = function(exts) {
  return orderKey(require.extensions, exts);
};


/*
  only for tests
 */

module.exports.__test__ = {
  orderKey: orderKey
};
