// Generated by CoffeeScript 1.9.2

/*
use under jest --runInBand
 */
jest.dontMock('./jest');

require('./jest');

jasmine.getEnv().afterEach(function() {
  if (!this.results().passed()) {
    process.env.JEST_BAIL = true;
    return this.env.specFilter = function() {};
  }
});

if (process.env.JEST_BAIL) {
  process.exit();
}
