// Generated by CoffeeScript 1.9.2
var compatible;

jest.dontMock('./core');

compatible = require('./core');

jasmine.getEnv().beforeEach(function() {
  return this.addMatchers({
    toBeCompatible: function(expects) {
      return (compatible(expects, this.actual)).isCompatible;
    }
  });
});
